// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.14.0
// source: hotspot-pb/hotspot.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HotspotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 版本号
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotspotRequest) Reset() {
	*x = HotspotRequest{}
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotspotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotspotRequest) ProtoMessage() {}

func (x *HotspotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotspotRequest.ProtoReflect.Descriptor instead.
func (*HotspotRequest) Descriptor() ([]byte, []int) {
	return file_hotspot_pb_hotspot_proto_rawDescGZIP(), []int{0}
}

func (x *HotspotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HotspotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HotspotItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotspotResponse) Reset() {
	*x = HotspotResponse{}
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotspotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotspotResponse) ProtoMessage() {}

func (x *HotspotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotspotResponse.ProtoReflect.Descriptor instead.
func (*HotspotResponse) Descriptor() ([]byte, []int) {
	return file_hotspot_pb_hotspot_proto_rawDescGZIP(), []int{1}
}

func (x *HotspotResponse) GetItems() []*HotspotItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type HotspotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotspotItem) Reset() {
	*x = HotspotItem{}
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotspotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotspotItem) ProtoMessage() {}

func (x *HotspotItem) ProtoReflect() protoreflect.Message {
	mi := &file_hotspot_pb_hotspot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotspotItem.ProtoReflect.Descriptor instead.
func (*HotspotItem) Descriptor() ([]byte, []int) {
	return file_hotspot_pb_hotspot_proto_rawDescGZIP(), []int{2}
}

func (x *HotspotItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HotspotItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HotspotItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_hotspot_pb_hotspot_proto protoreflect.FileDescriptor

var file_hotspot_pb_hotspot_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x68, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x2d, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x74,
	0x73, 0x70, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x22, 0x20, 0x0a, 0x0e, 0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0f, 0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x4f, 0x0a, 0x0b, 0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x32, 0x50, 0x0a, 0x0e, 0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x73,
	0x70, 0x6f, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f,
	0x74, 0x73, 0x70, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x74, 0x73, 0x70, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_hotspot_pb_hotspot_proto_rawDescOnce sync.Once
	file_hotspot_pb_hotspot_proto_rawDescData []byte
)

func file_hotspot_pb_hotspot_proto_rawDescGZIP() []byte {
	file_hotspot_pb_hotspot_proto_rawDescOnce.Do(func() {
		file_hotspot_pb_hotspot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotspot_pb_hotspot_proto_rawDesc), len(file_hotspot_pb_hotspot_proto_rawDesc)))
	})
	return file_hotspot_pb_hotspot_proto_rawDescData
}

var file_hotspot_pb_hotspot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hotspot_pb_hotspot_proto_goTypes = []any{
	(*HotspotRequest)(nil),  // 0: api.v1.HotspotRequest
	(*HotspotResponse)(nil), // 1: api.v1.HotspotResponse
	(*HotspotItem)(nil),     // 2: api.v1.HotspotItem
}
var file_hotspot_pb_hotspot_proto_depIdxs = []int32{
	2, // 0: api.v1.HotspotResponse.items:type_name -> api.v1.HotspotItem
	0, // 1: api.v1.HotspotService.GetHotspots:input_type -> api.v1.HotspotRequest
	1, // 2: api.v1.HotspotService.GetHotspots:output_type -> api.v1.HotspotResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotspot_pb_hotspot_proto_init() }
func file_hotspot_pb_hotspot_proto_init() {
	if File_hotspot_pb_hotspot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotspot_pb_hotspot_proto_rawDesc), len(file_hotspot_pb_hotspot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotspot_pb_hotspot_proto_goTypes,
		DependencyIndexes: file_hotspot_pb_hotspot_proto_depIdxs,
		MessageInfos:      file_hotspot_pb_hotspot_proto_msgTypes,
	}.Build()
	File_hotspot_pb_hotspot_proto = out.File
	file_hotspot_pb_hotspot_proto_goTypes = nil
	file_hotspot_pb_hotspot_proto_depIdxs = nil
}
