// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: hotspot-pb/hotspot.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HotspotService_GetHotspots_FullMethodName = "/api.v1.HotspotService/GetHotspots"
)

// HotspotServiceClient is the client API for HotspotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotspotServiceClient interface {
	GetHotspots(ctx context.Context, in *HotspotRequest, opts ...grpc.CallOption) (*HotspotResponse, error)
}

type hotspotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHotspotServiceClient(cc grpc.ClientConnInterface) HotspotServiceClient {
	return &hotspotServiceClient{cc}
}

func (c *hotspotServiceClient) GetHotspots(ctx context.Context, in *HotspotRequest, opts ...grpc.CallOption) (*HotspotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotspotResponse)
	err := c.cc.Invoke(ctx, HotspotService_GetHotspots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotspotServiceServer is the server API for HotspotService service.
// All implementations must embed UnimplementedHotspotServiceServer
// for forward compatibility.
type HotspotServiceServer interface {
	GetHotspots(context.Context, *HotspotRequest) (*HotspotResponse, error)
	mustEmbedUnimplementedHotspotServiceServer()
}

// UnimplementedHotspotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotspotServiceServer struct{}

func (UnimplementedHotspotServiceServer) GetHotspots(context.Context, *HotspotRequest) (*HotspotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotspots not implemented")
}
func (UnimplementedHotspotServiceServer) mustEmbedUnimplementedHotspotServiceServer() {}
func (UnimplementedHotspotServiceServer) testEmbeddedByValue()                        {}

// UnsafeHotspotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotspotServiceServer will
// result in compilation errors.
type UnsafeHotspotServiceServer interface {
	mustEmbedUnimplementedHotspotServiceServer()
}

func RegisterHotspotServiceServer(s grpc.ServiceRegistrar, srv HotspotServiceServer) {
	// If the following call pancis, it indicates UnimplementedHotspotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HotspotService_ServiceDesc, srv)
}

func _HotspotService_GetHotspots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotspotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotspotServiceServer).GetHotspots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotspotService_GetHotspots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotspotServiceServer).GetHotspots(ctx, req.(*HotspotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HotspotService_ServiceDesc is the grpc.ServiceDesc for HotspotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HotspotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.HotspotService",
	HandlerType: (*HotspotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotspots",
			Handler:    _HotspotService_GetHotspots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotspot-pb/hotspot.proto",
}
